name: formatted_text
description: >
  A simple text formatting package.
  Use to format text in TextField and Text widgets
version: 4.0.1
homepage: https://github.com/NirmalAriyathilake/formatted_text

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
